---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  CF_MANIFEST_HOST_TARGET:

inputs:
  - name: pcfdemo
  - name: candidate-release
  - name: version

outputs:
  - name: prepare-aws

run:
  path: pcfdemo/ci/tasks/prepare-aws.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-aws,
    --version-file, version/number,
    --input-manifest, pcfdemo/manifest.yml,
    --artifactId, pcf-demo,
    --packaging, war
  ]
